### ISSUE TITLE
missing or invalid authentication code

### ISSUE THREAD

**Issue by Rakshak1344** [Clancey/simple_auth#121]
I am facing this issue, help 
```
�🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".       
An Observatory debugger and profiler on sdk gphone x86 is available at:
http://127.0.0.1:54246/Eld-6Rp-yr0=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
E/flutter (11062): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: You are required to implement the 'showAuthenticator or sharedShowAuthenticator
E/flutter (11062): #0      AuthenticatedApi.authenticate (package:simple_auth/src/api/authenticatedApi.dart:27:7)
E/flutter (11062): <asynchronous suspension>
E/flutter (11062): #1      AuthenticatedApi.verifyCredentials (package:simple_auth/src/api/authenticatedApi.dart:51:25)
E/flutter (11062): #2      AuthenticatedApi.interceptRequest (package:simple_auth/src/api/authenticatedApi.dart:39:13)
E/flutter (11062): #3      Api.send (package:simple_auth/src/api/api.dart:89:17)
E/flutter (11062): #4      GoogleApi.getUserProfile (package:simple_auth/src/providers/google.dart:43:22)  
E/flutter (11062): #5      _MyHomePageState._incrementCounter (package:simpleauthflutter/main.dart:42:35)  
E/flutter (11062): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)E/flutter (11062): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (11062): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (11062): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11) 
E/flutter (11062): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5) 
E/flutter (11062): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (11062): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
```

**Comment by MaskyS** [comment]
You need to call SimpleAuthFlutter.init() as per the readme before you use the plugin, presumably in your initState() method.
