### ISSUE TITLE
Question about the callback activity

### ISSUE THREAD

**Issue by GroovinChip** [Clancey/simple_auth#18]
```
<activity android:name="clancey.simpleauth.simpleauthflutter.SimpleAuthCallbackActivity" >
            <intent-filter android:label="simple_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="com.googleusercontent.apps.992461286651-k3tsbcreniknqptanrugsetiimt0lkvo" />
            </intent-filter>
        </activity>
```

Is this what will take the user back to the app once they've authenticated? I'm trying to make my ap deep-linked so that when a user authorizes the app to connect to their GitHub account they get returned to the app rather than stay in the browser.

**Comment by GroovinChip** [comment]
I tried using a custom string (I used my app's package name) in both the githubApi object and in the settings for my GitHub Oauth app. I got errors in the console like that. Any suggestions?

**Comment by Clancey** [comment]
Can you paste the console output?

**Comment by GroovinChip** [comment]
Console output:
```
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): Failed to handle method call
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): java.lang.IllegalArgumentException: Unsupported value: java.net.URISyntaxException: Expected authority at index 45: com.groovinchip.fluttercommunitychallenges://
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at clancey.simpleauth.simpleauthflutter.SimpleAuthFlutterPlugin.onMethodCall(SimpleAuthFlutterPlugin.java:63)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#simple_auth_flutter/showAuthenticator(13047): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Code:
```
  final simpleAuth.GithubApi githubApi = simpleAuth.GithubApi(
    "github", "***",
    "***",
    "com.groovinchip.fluttercommunitychallenges://",
    scopes: [
      "user",
      "repo",
      "public_repo",
    ],
  );
```

**Comment by Clancey** [comment]
Does this happen when the UI is presented? Or after you login?

**Comment by GroovinChip** [comment]
it happens when I tap a button to log in

**Comment by GroovinChip** [comment]
Basically the button is supposed to launch the GitHub authorization, and once the app is authorize a FirebaseUser will be created

**Comment by Clancey** [comment]
My mistake on the redirect `com.groovinchip.fluttercommunitychallenges:/` only one `/` vs `//`

**Comment by GroovinChip** [comment]
now a blank webpage shows up instead of the github authentication, so weird. Do I only use `com.groovinchip.fluttercommunitychallenges:/` in my application or on the github side as well?

**Comment by Clancey** [comment]
That shouldn't matter. Blank page cloud be internet issue. I tested on my emulator and I got the log in page even with bogus data

**Comment by GroovinChip** [comment]
What's your backend configuration though? Do you use the same string from the code on the github side of things?
