### ISSUE TITLE
Azure AD example broken

### ISSUE THREAD

**Issue by abjorck** [Clancey/simple_auth#27]
Nothing happens when clicking login for azure, except logging of the following

```
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): Failed to handle method call
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): java.lang.IllegalArgumentException: Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at clancey.simpleauth.simpleauthflutter.SimpleAuthFlutterPlugin.onMethodCall(SimpleAuthFlutterPlugin.java:63)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/MethodChannel#simple_auth_flutter/showAuthenticator( 6889): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)


2018-10-03 17:26:45.119 7605-7605/com.example.simpleauthflutterexample E/MethodChannel#simple_auth_flutter/showAuthenticator: Failed to handle method call
    java.lang.IllegalArgumentException: Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
        at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
        at clancey.simpleauth.simpleauthflutter.SimpleAuthFlutterPlugin.onMethodCall(SimpleAuthFlutterPlugin.java:63)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2018-10-03 17:26:45.133 1390-1390/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7753728
2018-10-03 17:26:45.139 7605-7644/com.example.simpleauthflutterexample E/flutter: [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
    PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
    <asynchronous suspension>
    #2      SimpleAuthFlutter.showAuthenticator (package:simple_auth_flutter/simple_auth_flutter.dart:27:33)
    <asynchronous suspension>
    #3      OAuthApi.performAuthenticate (package:simple_auth/src/oauth/oauthApi.dart:86:30)
    <asynchronous suspension>
    #4      AuthenticatedApi.authenticate (package:simple_auth/src/api/authenticatedApi.dart:20:54)
    <asynchronous suspension>
    #5      _MyHomePageState.login (file:///Users/bjorck/Projects/safe/simple_auth/simple_auth_flutter_example/lib/main.dart:394:31)
    <asynchronous suspension>
    #6      _MyHomePageState.build.<anonymous closure> (file:///Users/bjorck/Projects/safe/simple_auth/simple_auth_flutter_example/lib/main.dart:133:15)
    #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
    #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
    #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
    #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
    #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
    #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
    #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
    #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
    #18     _invoke1 (dart:ui/hooks.dart:142:13)
    #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)
```

**Comment by Clancey** [comment]
So I need to handle this better. This is caused by a null redirect url. You need something in the redirect or this error happens.

**Comment by RakhimyanTim** [comment]
Hi there! let say I've some redirect url. Where I should set them?
