### ISSUE TITLE
 Unhandled Exception: Bad state: Future already completed

### ISSUE THREAD

**Issue by iBotPeaches** [Clancey/simple_auth#90]
So I wrote my own provider for an internal OAUTH system and it uses fragments in the URL, so I overrode the following function, which looks like a copy of a previous provider. I think Dropbox.

```
bool checkUrl(Uri url) {
    try {
      if (url.hasFragment && !url.hasQuery) {
        url = url.replace(query: url.fragment);
      }

      if (url?.host != redirectUri.host) return false;
      if (url?.query?.isEmpty ?? true) return false;
      if (!url.queryParameters.containsKey("access_token")) return false;

      var code = url.queryParameters["access_token"];
      if (code?.isEmpty ?? true) return false;

      token = code;
      foundAuthCode(code);
      return true;
    } catch (exception) {
      print(exception);
      return false;
    }
  }
```

What happens is `foundAuthCode` calls 

```
  ///Call this when you recieve the Auth token.
  void foundAuthCode(String authCode) {
    this.authCode = authCode;
    hasCompleted = true;
    _completer?.complete(authCode);
  }
```

Which the event of URL changing, triggers `UrlChange` which runs this.
```
    onUrlChanged.listen((UrlChange change) {
      var authenticator = authenticators[change.identifier];
      if (change.url == "canceled") {
        authenticator.cancel();
        return;
      } else if (change.url == "error") {
        authenticator.onError(change.description);
        return;
      }

      var uri = Uri.tryParse(change.url);
      if (authenticator.checkUrl(uri)) {
        _channel.invokeMethod("completed", {"identifier": change.identifier});
      } else if (change.foreComplete) {
        authenticator.onError("Unable to get an AuthToken from the server");
      }
    });
```

Which as you see runs `checkUrl` again. So I get a warning because the the `checkUrl` runs again, which runs method multiple times.

```
I/flutter ( 6110): Bad state: Future already completed
E/flutter ( 6110): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Future already completed
E/flutter ( 6110): #0      _Completer.completeError (dart:async/future_impl.dart:21:31)
E/flutter ( 6110): #1      Authenticator.onError (package:simple_auth/src/api/authenticator.dart:38:17)
E/flutter ( 6110): #2      SimpleAuthFlutter.init.<anonymous closure> (package:simple_auth_flutter/simple_auth_flutter.dart:76:23)
```

Did I implement this wrongly?

**Comment by iBotPeaches** [comment]
This was personal mistake. I was navigating to another page (without properly setting state), which was reloading the Login page, thus doing Login flow again thus above exception. Apologies.

**Comment by Nilesh-Chaudahri** [comment]
HI @iBotPeaches  how did you fix this can you help?

**Comment by iBotPeaches** [comment]
> HI @iBotPeaches how did you fix this. Can you help? i am not overriding any of this functions.

I haven't used Flutter in 3 years and my fix was in my original comment. Best I can help you with. Sorry.
